package com.lifeos.expense.domain;

import com.lifeos.expense.domain.ExpenseEnums.TxType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.UUID;

@Entity
@Table(name = "transaction", schema = "expense", indexes = {
        @Index(name = "idx_tx_user_date", columnList = "user_id,occurred_on"),
        @Index(name = "idx_tx_account", columnList = "account_id,occurred_on"),
        @Index(name = "idx_tx_category", columnList = "category_id,occurred_on")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Transaction {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "user_id", nullable = false)
    private UUID userId;

    @Column(name = "account_id", nullable = false)
    private UUID accountId;

    /** Destination account; only set for TRANSFER. */
    @Column(name = "to_account_id")
    private UUID toAccountId;

    @Column(name = "category_id")
    private UUID categoryId;

    /** Always stored positive; {@link #type} carries the direction. */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    @Column(nullable = false, length = 3)
    @Builder.Default
    private String currency = "VND";

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private TxType type;

    @Column(name = "occurred_on", nullable = false)
    private LocalDate occurredOn;

    @Column(length = 500)
    private String note;

    @Column(length = 120)
    private String merchant;

    @ElementCollection(fetch = FetchType.EAGER)
    @CollectionTable(name = "transaction_tags", schema = "expense", joinColumns = @JoinColumn(name = "transaction_id"))
    @Column(name = "tag", length = 40)
    @Builder.Default
    private Set<String> tags = new LinkedHashSet<>();

    /** Set when the row was generated by a recurring rule rather than typed by hand. */
    @Column(name = "recurring_rule_id")
    private UUID recurringRuleId;

    @Column(name = "created_at", nullable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private Instant updatedAt = Instant.now();

    /** Signed value for cash-flow maths: negative for spend, positive for income. */
    public BigDecimal signedAmount() {
        return type == TxType.INCOME ? amount : amount.negate();
    }
}
